"""Phase 2 seed data — Workout Groups + Exercise Library.

Called once from main.py after table creation.
Checks for existing data before inserting to stay idempotent.
"""

import logging
from sqlalchemy.orm import Session
from app import models

logger = logging.getLogger(__name__)


# ── Workout Groups ──────────────────────────────────────────────────────

WORKOUT_GROUPS = [
    dict(
        group_name="Beginner Foundation",
        description="Foundational movement patterns for complete beginners with no major injuries.",
        target_fitness_level="Beginner",
        primary_goal="General Fitness",
        allowed_risk_level="Low",
        default_weekly_frequency=3,
        default_session_duration=45,
        default_intensity_range="Low",
        equipment_required="Bodyweight, Resistance bands, Mat",
        injury_restrictions="No high-impact movements. Avoid heavy loading.",
        group_notes="Focus on technique, mobility and confidence. Build base fitness over 8 weeks.",
        status="Active",
    ),
    dict(
        group_name="Beginner Fat Loss",
        description="Calorie-burning circuit training for beginners focused on fat loss.",
        target_fitness_level="Beginner",
        primary_goal="Fat Loss",
        allowed_risk_level="Low",
        default_weekly_frequency=4,
        default_session_duration=45,
        default_intensity_range="Moderate",
        equipment_required="Bodyweight, Dumbbells (light), Cardio equipment",
        injury_restrictions="No jumping or high-impact movements in first 4 weeks.",
        group_notes="Progressive overload applied week by week. Track weight and waist weekly.",
        status="Active",
    ),
    dict(
        group_name="Low-Impact Fat Loss",
        description="Fat loss training with zero high-impact loading. Suitable for knee/joint issues.",
        target_fitness_level="Beginner",
        primary_goal="Fat Loss",
        allowed_risk_level="Medium",
        default_weekly_frequency=4,
        default_session_duration=50,
        default_intensity_range="Moderate",
        equipment_required="Resistance bands, Dumbbells, Bike or rower",
        injury_restrictions="NO jumping, running, or high-impact movements. Knee-safe only.",
        group_notes="Uses seated, standing, and lying exercises only. Great for knee pain, overweight beginners.",
        status="Active",
    ),
    dict(
        group_name="Strength Builder",
        description="Progressive strength training using compound lifts and dumbbells.",
        target_fitness_level="Intermediate",
        primary_goal="Strength",
        allowed_risk_level="Low",
        default_weekly_frequency=4,
        default_session_duration=60,
        default_intensity_range="High",
        equipment_required="Barbell, Dumbbells, Kettlebells, Resistance bands",
        injury_restrictions="Medical clearance required before heavy barbell work.",
        group_notes="Linear periodisation over 12 weeks. Deload every 4th week.",
        status="Active",
    ),
    dict(
        group_name="Mobility and Rehab",
        description="Rehabilitation and mobility restoration for members recovering from injury or surgery.",
        target_fitness_level="Beginner",
        primary_goal="Rehabilitation",
        allowed_risk_level="High with caution",
        default_weekly_frequency=3,
        default_session_duration=40,
        default_intensity_range="Low",
        equipment_required="Mat, Resistance bands, Foam roller",
        injury_restrictions="No loading without medical clearance. Coach-supervised only.",
        group_notes="Pair with physiotherapy where applicable. Focus on pain-free movement patterns.",
        status="Active",
    ),
    dict(
        group_name="Sports Performance",
        description="Athletic conditioning for sport-specific performance and power development.",
        target_fitness_level="Advanced",
        primary_goal="Sports Performance",
        allowed_risk_level="Low",
        default_weekly_frequency=5,
        default_session_duration=75,
        default_intensity_range="High",
        equipment_required="Full gym access, Kettlebells, Battle ropes, Cardio equipment",
        injury_restrictions="Full medical clearance required. No active injuries.",
        group_notes="Periodised for sports season. Includes strength, conditioning, mobility and recovery.",
        status="Active",
    ),
    dict(
        group_name="Busy Professional",
        description="Efficient 30–45 min sessions for members with limited time.",
        target_fitness_level="Intermediate",
        primary_goal="General Fitness",
        allowed_risk_level="Low",
        default_weekly_frequency=3,
        default_session_duration=35,
        default_intensity_range="Moderate",
        equipment_required="Dumbbells, Resistance bands, Bodyweight",
        injury_restrictions="None. Adaptable based on individual profile.",
        group_notes="Short, dense workouts. Supersets and circuits. Minimal rest times.",
        status="Active",
    ),
    dict(
        group_name="Advanced Athlete",
        description="High-intensity training for advanced or elite-level athletes.",
        target_fitness_level="Athlete",
        primary_goal="Muscle Gain",
        allowed_risk_level="Low",
        default_weekly_frequency=5,
        default_session_duration=90,
        default_intensity_range="High",
        equipment_required="Full gym access required",
        injury_restrictions="Full screening required. No compromised movements.",
        group_notes="Advanced programming. Requires consistent baseline fitness assessment.",
        status="Active",
    ),
]


# ── Exercise Library ────────────────────────────────────────────────────

EXERCISES = [
    # ── Warm-up ────────────────────────────────────────────
    dict(
        exercise_name="Jumping Jacks", exercise_category="Warm-up",
        primary_muscle_group="Full Body", movement_type="Locomotion",
        equipment_needed="Bodyweight", difficulty_level="Beginner",
        impact_level="Medium", default_sets=2, default_reps=30,
        default_rest_seconds=30,
        instructions="Stand with feet together. Jump while spreading arms and legs. Return to start.",
        coach_cues="Land softly. Keep core engaged. Arms stay straight.",
        safety_notes="High-impact. Avoid with knee or ankle injuries.",
        avoid_if_knee_injury=True, avoid_if_pregnant=True,
        low_impact=False, beginner_friendly=True,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="High Knees", exercise_category="Warm-up",
        primary_muscle_group="Hip Flexors, Quads", movement_type="Locomotion",
        equipment_needed="Bodyweight", difficulty_level="Beginner",
        impact_level="Medium", default_sets=2, default_duration_seconds=30,
        default_rest_seconds=20,
        instructions="Run in place driving knees above hip level alternately.",
        coach_cues="Drive arms with knees. Stay on balls of feet. Tall posture.",
        avoid_if_knee_injury=True, low_impact=False, beginner_friendly=True,
        track_time=True, track_sets=True,
    ),
    dict(
        exercise_name="Arm Circles", exercise_category="Warm-up",
        primary_muscle_group="Shoulders, Rotator Cuff", movement_type="Mobility",
        equipment_needed="Bodyweight", difficulty_level="Beginner",
        impact_level="Low", default_sets=2, default_reps=15,
        instructions="Extend arms at shoulder height. Make forward then backward circles.",
        coach_cues="Keep arms straight. Full range of motion. Progress from small to large circles.",
        avoid_if_shoulder_injury=False, low_impact=True, beginner_friendly=True,
        track_reps=True, track_sets=True,
    ),
    # ── Mobility ───────────────────────────────────────────
    dict(
        exercise_name="Cat-Cow Stretch", exercise_category="Mobility",
        primary_muscle_group="Spine, Thoracic", movement_type="Mobility",
        equipment_needed="Mat", difficulty_level="Beginner",
        impact_level="Low", default_sets=2, default_reps=10,
        default_rest_seconds=15,
        instructions="On all-fours. Arch back (cow) then round back (cat). Breathe through each.",
        coach_cues="Move with breath. Full spinal range. Neutral wrists.",
        low_impact=True, beginner_friendly=True,
        avoid_if_lower_back_pain=False,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="Hip Flexor Stretch", exercise_category="Mobility",
        primary_muscle_group="Hip Flexors", movement_type="Mobility",
        equipment_needed="Mat", difficulty_level="Beginner",
        impact_level="Low", default_sets=2, default_reps=1,
        default_duration_seconds=45,
        instructions="Kneel on one knee. Push hips forward gently. Hold. Switch sides.",
        coach_cues="Keep torso tall. Don't hyperextend lower back. Feel stretch in front of hip.",
        low_impact=True, beginner_friendly=True,
        track_time=True, track_sets=True,
    ),
    dict(
        exercise_name="Hamstring Stretch", exercise_category="Mobility",
        primary_muscle_group="Hamstrings", movement_type="Mobility",
        equipment_needed="Mat", difficulty_level="Beginner",
        impact_level="Low", default_sets=2, default_duration_seconds=45,
        instructions="Sit or stand. Straighten one leg. Hinge forward from hips to feel the stretch.",
        coach_cues="Don't round the lower back. Feel pull in the back of the thigh.",
        low_impact=True, beginner_friendly=True,
        avoid_if_lower_back_pain=False,
        track_time=True, track_sets=True,
    ),
    dict(
        exercise_name="Shoulder Mobility Drill", exercise_category="Mobility",
        primary_muscle_group="Shoulders, Thoracic", movement_type="Mobility",
        equipment_needed="Resistance bands", difficulty_level="Beginner",
        impact_level="Low", default_sets=3, default_reps=12,
        instructions="Use band. Pull apart at chest height. Squeeze shoulder blades.",
        coach_cues="Keep arms straight. Controlled movement. Don't shrug.",
        low_impact=True, beginner_friendly=True,
        avoid_if_shoulder_injury=False,
        track_reps=True, track_sets=True,
    ),
    # ── Strength ───────────────────────────────────────────
    dict(
        exercise_name="Bodyweight Squat", exercise_category="Strength",
        primary_muscle_group="Quads, Glutes", secondary_muscle_groups="Hamstrings, Core",
        movement_type="Squat", equipment_needed="Bodyweight",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=15, default_rest_seconds=60,
        instructions="Feet shoulder-width. Push hips back and down. Thighs parallel. Drive through heels.",
        coach_cues="Chest up. Knees track over toes. Full depth. Weight in heels.",
        common_mistakes="Knees caving in. Heels lifting. Rounding back.",
        low_impact=True, beginner_friendly=True,
        avoid_if_knee_injury=False,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="Goblet Squat", exercise_category="Strength",
        primary_muscle_group="Quads, Glutes", secondary_muscle_groups="Core, Hamstrings",
        movement_type="Squat", equipment_needed="Dumbbells",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=12, default_rest_seconds=60,
        instructions="Hold dumbbell at chest. Squat deep. Elbows inside knees at bottom.",
        coach_cues="Use weight to counterbalance. Chest stays tall. Deep squat position.",
        common_mistakes="Weight drifting forward. Not hitting depth.",
        low_impact=True, beginner_friendly=True,
        track_reps=True, track_sets=True, track_weight=True,
    ),
    dict(
        exercise_name="Incline Push-up", exercise_category="Strength",
        primary_muscle_group="Chest, Triceps", secondary_muscle_groups="Shoulders, Core",
        movement_type="Push", equipment_needed="Bodyweight",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=12, default_rest_seconds=60,
        instructions="Hands on bench/wall. Push-up at angle. Lower chest to surface.",
        coach_cues="Straight body line. Elbows at 45°. Full range.",
        low_impact=True, beginner_friendly=True,
        avoid_if_shoulder_injury=True,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="Dumbbell Row", exercise_category="Strength",
        primary_muscle_group="Lats, Rhomboids", secondary_muscle_groups="Biceps, Rear Deltoid",
        movement_type="Pull", equipment_needed="Dumbbells",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=12, default_rest_seconds=60,
        instructions="Brace one hand on bench. Row dumbbell to hip. Squeeze back at top.",
        coach_cues="Lead with elbow, not hand. Keep torso flat. Don't rotate hips.",
        common_mistakes="Rotating torso. Using too much weight.",
        low_impact=True, beginner_friendly=True,
        avoid_if_shoulder_injury=False,
        avoid_if_lower_back_pain=False,
        track_reps=True, track_sets=True, track_weight=True,
    ),
    dict(
        exercise_name="Glute Bridge", exercise_category="Strength",
        primary_muscle_group="Glutes", secondary_muscle_groups="Hamstrings, Core",
        movement_type="Hinge", equipment_needed="Mat",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=15, default_rest_seconds=45,
        instructions="Lie on back. Feet flat. Drive hips up. Squeeze glutes at top. Lower slowly.",
        coach_cues="Squeeze glutes, don't just thrust hips. Keep ribs down.",
        low_impact=True, beginner_friendly=True,
        avoid_if_lower_back_pain=False,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="Kettlebell Deadlift", exercise_category="Strength",
        primary_muscle_group="Hamstrings, Glutes", secondary_muscle_groups="Spinal Erectors, Core",
        movement_type="Hinge", equipment_needed="Kettlebells",
        difficulty_level="Intermediate", impact_level="Low",
        default_sets=4, default_reps=8, default_rest_seconds=90,
        instructions="Hinge at hips. Soft knee bend. Grip KB. Drive hips forward to stand.",
        coach_cues="Neutral spine throughout. Push floor away. Hips and shoulders rise together.",
        common_mistakes="Rounding lower back. Squatting instead of hinging.",
        safety_notes="Technique critical. Assess form before loading.",
        low_impact=True, beginner_friendly=False,
        avoid_if_lower_back_pain=True,
        medical_clearance_recommended=False,
        track_reps=True, track_sets=True, track_weight=True,
    ),
    dict(
        exercise_name="Dumbbell Shoulder Press", exercise_category="Strength",
        primary_muscle_group="Deltoids", secondary_muscle_groups="Triceps, Upper Traps",
        movement_type="Push", equipment_needed="Dumbbells",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=10, default_rest_seconds=60,
        instructions="Seated or standing. Dumbbells at shoulder. Press overhead. Lower controlled.",
        coach_cues="Don't flare elbows excessively. Slight core brace. Full lockout.",
        avoid_if_shoulder_injury=True,
        low_impact=True, beginner_friendly=True,
        track_reps=True, track_sets=True, track_weight=True,
    ),
    dict(
        exercise_name="Walking Lunges", exercise_category="Strength",
        primary_muscle_group="Quads, Glutes", secondary_muscle_groups="Hamstrings, Core",
        movement_type="Squat", equipment_needed="Bodyweight",
        difficulty_level="Beginner", impact_level="Medium",
        default_sets=3, default_reps=12, default_rest_seconds=60,
        instructions="Step forward, lower back knee toward floor. Drive up and step into next lunge.",
        coach_cues="90-90 at bottom. Front knee over ankle. Torso tall.",
        avoid_if_knee_injury=True,
        low_impact=False, beginner_friendly=True,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="Farmer's Carry", exercise_category="Conditioning",
        primary_muscle_group="Grip, Forearms", secondary_muscle_groups="Traps, Core, Glutes",
        movement_type="Carry", equipment_needed="Dumbbells",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_duration_seconds=30,
        default_rest_seconds=60,
        instructions="Hold heavy dumbbells at sides. Walk in controlled steps. Stay tall.",
        coach_cues="Don't lean to one side. Shoulders back and down. Small steps.",
        low_impact=True, beginner_friendly=True,
        track_time=True, track_sets=True, track_weight=True,
    ),
    # ── Core ───────────────────────────────────────────────
    dict(
        exercise_name="Plank", exercise_category="Core",
        primary_muscle_group="Core, Transverse Abdominis", secondary_muscle_groups="Glutes, Shoulder stabilisers",
        movement_type="Anti-rotation", equipment_needed="Mat",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_duration_seconds=30, default_rest_seconds=45,
        instructions="Forearm or straight arm plank. Body in straight line. Hold position.",
        coach_cues="Hips level. Don't sag. Squeeze glutes. Breathe.",
        low_impact=True, beginner_friendly=True,
        avoid_if_shoulder_injury=False,
        track_time=True, track_sets=True,
    ),
    dict(
        exercise_name="Side Plank", exercise_category="Core",
        primary_muscle_group="Obliques, Hip Abductors", secondary_muscle_groups="Core",
        movement_type="Anti-rotation", equipment_needed="Mat",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=2, default_duration_seconds=25, default_rest_seconds=30,
        instructions="Forearm on floor, side position. Stack feet or modify with knee down. Hold.",
        coach_cues="Hip stays elevated. Straight body line. Don't rotate forward.",
        low_impact=True, beginner_friendly=True,
        track_time=True, track_sets=True,
    ),
    dict(
        exercise_name="Dead Bug", exercise_category="Core",
        primary_muscle_group="Deep Core", secondary_muscle_groups="Hip Flexors",
        movement_type="Anti-rotation", equipment_needed="Mat",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=8, default_rest_seconds=45,
        instructions="Lie on back. Arms up, knees at 90°. Lower opposite arm and leg slowly. Return. Switch.",
        coach_cues="Press lower back to floor throughout. Move slowly. Breathe out as you lower.",
        low_impact=True, beginner_friendly=True,
        avoid_if_lower_back_pain=False,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="Bird Dog", exercise_category="Core",
        primary_muscle_group="Spinal Erectors, Glutes", secondary_muscle_groups="Core",
        movement_type="Balance", equipment_needed="Mat",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=8, default_rest_seconds=30,
        instructions="All-fours. Extend opposite arm and leg. Hold 2 sec. Return. Alternate.",
        coach_cues="Don't rotate hips. Keep back flat. Slow controlled movement.",
        low_impact=True, beginner_friendly=True,
        track_reps=True, track_sets=True,
    ),
    # ── Cardio ─────────────────────────────────────────────
    dict(
        exercise_name="Stationary Bike", exercise_category="Cardio",
        primary_muscle_group="Quads, Hamstrings", secondary_muscle_groups="Glutes, Cardiovascular",
        movement_type="Locomotion", equipment_needed="Cardio equipment",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=1, default_duration_seconds=1200,
        default_rest_seconds=0,
        instructions="Set comfortable resistance. Maintain cadence 60–80 rpm. Steady state.",
        coach_cues="Seat at hip height. Light grip. Consistent cadence.",
        low_impact=True, beginner_friendly=True,
        track_time=True, track_heart_rate=True, track_rpe=True,
    ),
    dict(
        exercise_name="Treadmill Walk", exercise_category="Cardio",
        primary_muscle_group="Full Body, Cardiovascular", movement_type="Locomotion",
        equipment_needed="Cardio equipment", difficulty_level="Beginner",
        impact_level="Low", default_sets=1, default_duration_seconds=1200,
        instructions="Walk at comfortable pace. Slight incline for added intensity.",
        coach_cues="Natural arm swing. Upright posture. Avoid holding rails.",
        low_impact=True, beginner_friendly=True,
        track_time=True, track_distance=True, track_heart_rate=True, track_rpe=True,
    ),
    dict(
        exercise_name="Mountain Climbers", exercise_category="Cardio",
        primary_muscle_group="Core, Hip Flexors", secondary_muscle_groups="Shoulders, Cardiovascular",
        movement_type="Locomotion", equipment_needed="Bodyweight",
        difficulty_level="Beginner", impact_level="Medium",
        default_sets=3, default_duration_seconds=30, default_rest_seconds=30,
        instructions="Push-up position. Drive knees to chest alternately at pace.",
        coach_cues="Hips stay level. Shoulders over wrists. Consistent tempo.",
        avoid_if_shoulder_injury=True, avoid_if_lower_back_pain=True,
        low_impact=False, beginner_friendly=True,
        track_time=True, track_sets=True, track_rpe=True,
    ),
    # ── Conditioning ───────────────────────────────────────
    dict(
        exercise_name="Battle Ropes", exercise_category="Conditioning",
        primary_muscle_group="Shoulders, Arms", secondary_muscle_groups="Core, Cardiovascular",
        movement_type="Locomotion", equipment_needed="Other",
        difficulty_level="Intermediate", impact_level="Low",
        default_sets=4, default_duration_seconds=20, default_rest_seconds=40,
        instructions="Hold rope ends. Alternate arms in wave motion at consistent pace.",
        coach_cues="Slight hinge position. Power from hips. Arms loose not stiff.",
        avoid_if_shoulder_injury=True,
        low_impact=True, beginner_friendly=False,
        track_time=True, track_sets=True, track_rpe=True,
    ),
    dict(
        exercise_name="Step-ups", exercise_category="Conditioning",
        primary_muscle_group="Quads, Glutes", secondary_muscle_groups="Hamstrings, Balance",
        movement_type="Squat", equipment_needed="Bodyweight",
        difficulty_level="Beginner", impact_level="Low",
        default_sets=3, default_reps=12, default_rest_seconds=45,
        instructions="Step onto box. Drive through front heel. Stand tall. Step down. Alternate.",
        coach_cues="Don't push off the back foot. Full hip extension at top.",
        avoid_if_knee_injury=False,
        low_impact=True, beginner_friendly=True,
        track_reps=True, track_sets=True,
    ),
    dict(
        exercise_name="Resistance Band Pull-aparts", exercise_category="Conditioning",
        primary_muscle_group="Rear Deltoids, Rhomboids", movement_type="Pull",
        equipment_needed="Resistance bands", difficulty_level="Beginner",
        impact_level="Low", default_sets=3, default_reps=15, default_rest_seconds=30,
        instructions="Hold band at chest width. Pull apart horizontally. Squeeze shoulder blades.",
        coach_cues="Arms straight. Control the return. Squeeze at full extension.",
        low_impact=True, beginner_friendly=True,
        avoid_if_shoulder_injury=False,
        track_reps=True, track_sets=True,
    ),
    # ── Cool-down ───────────────────────────────────────────
    dict(
        exercise_name="Cool-down Walk", exercise_category="Cool-down",
        primary_muscle_group="Full Body", movement_type="Locomotion",
        equipment_needed="Bodyweight", difficulty_level="Beginner",
        impact_level="Low", default_sets=1, default_duration_seconds=300,
        instructions="Walk slowly for 5 minutes. Gradually reduce heart rate.",
        coach_cues="Deep breaths. Natural pace. Let body recover.",
        low_impact=True, beginner_friendly=True,
        track_time=True,
    ),
    dict(
        exercise_name="Quad Stretch", exercise_category="Cool-down",
        primary_muscle_group="Quadriceps", movement_type="Mobility",
        equipment_needed="Bodyweight", difficulty_level="Beginner",
        impact_level="Low", default_sets=2, default_duration_seconds=40,
        instructions="Stand on one leg. Pull opposite foot toward glute. Hold. Switch.",
        coach_cues="Stand tall. Don't lean forward. Pull ankle, not foot.",
        low_impact=True, beginner_friendly=True,
        avoid_if_knee_injury=False,
        track_time=True, track_sets=True,
    ),
    dict(
        exercise_name="Child's Pose", exercise_category="Cool-down",
        primary_muscle_group="Spine, Lats, Hips", movement_type="Mobility",
        equipment_needed="Mat", difficulty_level="Beginner",
        impact_level="Low", default_sets=1, default_duration_seconds=60,
        instructions="Kneel and sit back on heels. Arms extended forward. Hold.",
        coach_cues="Breathe deeply. Relax into the stretch. Arms fully extended.",
        low_impact=True, beginner_friendly=True,
        track_time=True,
    ),
]


# ── Seeder function ─────────────────────────────────────────────────────

def seed_phase2(db: Session) -> None:
    """Insert workout groups and exercises if the tables are empty."""

    # Workout groups
    if db.query(models.WorkoutGroup).count() == 0:
        for data in WORKOUT_GROUPS:
            db.add(models.WorkoutGroup(**data))
        db.commit()
        logger.info("Seeded %d workout groups.", len(WORKOUT_GROUPS))
    else:
        logger.debug("Workout groups already seeded — skipping.")

    # Exercises
    if db.query(models.ExerciseLibrary).count() == 0:
        for data in EXERCISES:
            db.add(models.ExerciseLibrary(**data))
        db.commit()
        logger.info("Seeded %d exercises.", len(EXERCISES))
    else:
        logger.debug("Exercise library already seeded — skipping.")
